add_user:
	poetry run python ./add_user.py
change_password:
	poetry run python ./change_password.py
remove_folder:
	poetry run python ./remove_folder.py
remove_user:
	poetry run python ./remove_user.py
reset_user_auth:
	poetry run python ./reset_user_auth.py
bulk_new_users:
	poetry run python ./bulk_new_users.py
